#ifndef FS_ERROR_H
#define FS_ERROR_H

typedef enum {
    FS_FAILED = 0,
    FS_OK = 1,
    FILE_FAILED = 2,
    FILE_OK = 3,
    FILE_MEMORY_ALLOCATION_FAILED = 4,
    FILE_NOT_FOUND = 5,
    FILE_ALREADY_EXISTS = 6,
    DIR_OK = 7,
    DIR_MEMORY_ALLOCATION_FAILED = 8,
    DIR_NOT_FOUND = 9,
    DIR_ALREADY_EXISTS = 10,
    PATH_FAILED = 11,
    PATH_OK = 12,
    CURRENT_DIR_FAILED = 13,
    FILE_CREATION_FAILED = 14,
    INVALID_DIR_NAME = 15,
    STACK_EMPTY = 16,
    POP_ROOT_FAILURE = 17,
    DELETING_ROOT_DIR_ERROR = 18,
    MOVE_OK = 19,
    MOVE_FAILED = 20,
    CANNOT_MOVE_TO_IT_SELF = 21,
    DEST_ALREADY_EXISTS = 22,
    ITEM_IS_NOT_FILE_OR_DIR = 23
}FS_ERROR;
#endif